# Generated by Django 2.1.3 on 2018-11-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['label_text']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='label',
            field=models.ManyToManyField(to='blog.Label'),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_text',
            field=models.CharField(max_length=50, verbose_name='Label'),
        ),
    ]
