# Generated by Django 2.1.3 on 2018-11-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181124_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-modified_at'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='label',
            name='label_text',
        ),
        migrations.AddField(
            model_name='label',
            name='name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
