# Generated by Django 2.1.3 on 2018-11-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181124_2350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-modified_at']},
        ),
    ]
